---
- name: Desktop configuration
  hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
  - name: Install packages
    package: 
      name:
        - zsh
        - htop
        - tmux
        - virtualbox
        - vagrant
        - openssh-server
        - net-tools
        - git
        - mc
        - gitk
        - git-gui
        - xrdp
        - python
        - vim 
  - name: copy sudoers_gabor
    copy: src=files/sudoers_gabor dest=/etc/sudoers.d/gabor owner=root group=root mode=0440
  - name: Create ssh key
    user:
      name: gabor
      state: present
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa
  - name: Configure git e-mail
    git_config:
      name: user.email
      scope: global
      value: 'galbitz@gmail.com'
    become: false
  - name: Configure git name
    git_config:
      name: user.name
      scope: global
      value: 'Gabor A'
    become: false
  - name: Add authorized keys
    authorized_key:
      user: gabor
      state: present
      key: https://github.com/galbitz.keys
  # - name: Download DWService client
  #   get_url:
  #     url: https://www.dwservice.net/download/dwagent_generic.sh
  #     dest: /tmp/
  # - name: Install dwservice
  #   command: sh /tmp/dwagent.sh -silent key=530-766-080
  #   register: dwservice
  # - debug: msg="{{ dwservice.stdout }}"
  # - debug: msg="{{ dwservice.stderr }}"
  # - name: Config gdm to support dwservice
  #   lineinfile:
  #     path: /etc/gdm3/custom.conf
  #     regexp: '^#WaylandEnable=false'
  #     line: 'WaylandEnable=false'
  #   notify: restart_display
  # handlers:
  #   - name: restart_display manager
  #     service:
  #       name: display-manager.service
  #       state: restarted

