---
- name: Install core packages
  package: 
    name:
      - zsh
      - htop
      - tmux
      - virtualbox
      - vagrant
      - openssh-server
      - net-tools
      - git
      - mc
      - gitk
      - git-gui
      - xrdp
      - python
      - vim 