---
username: gabor
email: galbitz@gmail.com
fullname: 'Gabor A'
keyurl: https://github.com/galbitz.keys
password_hash: $6$ysilslH/mUe3tyJi$Fpjhe1WJPdnYc.hDhn18WIe.ujwyhJTJfdAvbxd7LsSeYCV018BJ76j/lX4WmiQPZpZFnbWUy1cdHe.DeM46t1

oh_my_zsh_theme: robbyrussell
oh_my_zsh_plugins:
  - git